### ISSUE TITLE
Support for InfluxDB 1.x ?

### ISSUE THREAD

**Issue by davidshrive** [mvantassel/plexpy2influx#1]
Hey,

After wondering why this wasn't working for me I realised the influxDB node library used doesn't support the latest version.

Any plans to update this to support the latest influxDB?

Thanks

**Comment by mvantassel** [comment]
@davidshrive I've updated the node-influx library to v5 which supports newer influx instances. Have a look and see if that resolves the issue for you.

I'm currently using the influx docker instance which is not v1 so I can't test this without some setup.

Thanks!

**Comment by davidshrive** [comment]
Thanks for the quick response. Still not working though.

```
npm info it worked if it ends with ok
npm info using npm@2.15.9
npm info using node@v4.5.0
npm info prestart plexpy2influx@0.1.6
npm info start plexpy2influx@0.1.6

> plexpy2influx@0.1.6 start /usr/src/app
> node plexpy2influx.js

No sessions to log: Sun Feb 12 2017 14:34:39 GMT+0000 (GMT)
[TypeError: influxClient.writePoint is not a function]
Unhandled rejection TypeError: influxClient.writePoint is not a function
at writeToInflux (/usr/src/app/plexpy2influx.js:51:25)
at /usr/src/app/plexpy2influx.js:151:9
at Array.forEach (native)
at onGetPlexPyUsersData (/usr/src/app/plexpy2influx.js:144:15)
at tryCatcher (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:691:18)
at Async._drainQueue (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I say this without every using javascript but it appears this function has been renamed to `writePoints` and the params have changed.

https://github.com/node-influx/node-influx/blob/2c478f766f3ef9ec8ddfd20483e88bd7311db80e/src/index.ts#L943

**Comment by mvantassel** [comment]
Apologies the api changed to writeMeasurement. I didn't catch that. I just tested it locally and it's working now!

**Comment by davidshrive** [comment]
Amazing, can you push the latest version to docker hub please!

**Comment by mvantassel** [comment]
I pushed it when I committed the changes. Just grab the latest and you're good to go :)

-- I pushed it again just now to ensure it has all the latest commits
