### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by animosity022** [mvantassel/plexpy2influx#16]
I apologize as I'm a decent Linux guy, but not a docker guy at all.  I was taking a look at this as getting my plexpy data into influx for graphing looked pretty cool to setup.

I was trying to just run the docker and I get some issues.

I tried just doing the run command, but I wasn't able to figure out how to add the repository properly as it searched but didn't find it.

I finally figured out how to build it and got it built from git cloning the repo. Once built, I got an error that:

```
[root@plex plexpy2influx]# docker run -e PLEXPY_TOKEN="KEY" plexpy2influxdb
module.js:327
    throw err;
    ^

Error: Cannot find module 'influx'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/plexpy2influx.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

If there is an easier way to start up the docker and get it going, I've googled for a bit and just haven't figured it out. I'm running Fedora 27 as well.

**Comment by mvantassel** [comment]
Hey @animosity22, 

The built image is up on dockerhub @ https://hub.docker.com/r/matthewvantassel/plexpy2influx/

You may have better luck using that `docker pull matthewvantassel/plexpy2influx`. Thats how I run it myself.

Thanks!
